model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 100001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: taming.data.h5py.H5PyDatasetTrain
      params:
        config:
          size: 64
          data_path: /home/wilson/data/bair.hdf5
    validation:
      target: taming.data.h5py.H5PyDatasetTest
      params:
        config:
          size: 64
          data_path: /home/wilson/data/bair.hdf5
